name: flixstar
description: "A Movies Streaming app"
publish_to: "none"

version: 1.0.2+102

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  tmdb_api: ^2.2.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4
  dio: ^5.4.3+1
  # pretty_dio_logger: ^1.3.1
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  get: ^4.6.6
  responsive_grid_list: ^1.4.0
  getwidget: ^4.0.0
  load_items: ^0.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  jikan_api: ^2.2.1
  get_it: ^7.7.0
  share_plus: ^9.0.0
  # river_player: ^0.1.3
  html: ^0.15.4
  easy_web_view: ^2.0.2
  keymap: ^0.0.5
  fullscreen_window: ^1.0.4
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  package_info_plus: ^8.0.0
  google_mobile_ads: ^5.1.0
  version: ^3.0.2
  firebase_analytics: ^11.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
