on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "18"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install js-yaml
      - name: Install js-yaml
        run: npm install js-yaml

      # Extract version from pubspec.yaml
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: node get-version.js

      # Clean Cache
      - name: Clean Cache
        run: flutter clean

      # Get Packages
      - name: Get Packages
        run: flutter pub get


      # Build APK
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # Build Web
      - name: Build Web
        run: flutter build web

      # Adjust Base HREF
      - name: Adjust Base HREF
        run: sed -i 's|<base href="/">|<base href="/flixstar/">|' build/web/index.html

      # Deploy To GitHub Pages
      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:
            ./build/web

      # Push to Releases
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ steps.extract_version.outputs.version }}
          token: ${{ secrets.TOKEN }}
